# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='opensubtitles-dataloader',
    version='0.1.3',
    python_requires='==3.*,>=3.5.0',
    author='Christoph Minixhofer',
    author_email='christoph.minixhofer@gmail.com',
    entry_points={
        "console_scripts": [
            "opensubtitles-download = opensubtitles_dataloader.__main__:download"
        ]
    },
    packages=['opensubtitles_dataloader'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'click==7.*,>=7.1.2', 'numpy==1.*,>=1.0.0', 'torch==1.*,>=1.0.0',
        'tqdm==4.*,>=4.0.0'
    ],
    extras_require={"dev": ["pytest==3.*,>=3.0.0"]},
)
